### PR TITLE
Fix meta tags

### PR DESCRIPTION
**Pull request by aramshiva**
Fix meta tags causing the following error:
```
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
```

### CODE REVIEW

**Comment by jaspermayone** [comment]
oh i need to fix this on dev too

**Comment by jaspermayone** [comment]
ty

**Comment by jaspermayone** [comment]
oh wait that was dev lol

**Comment by jaspermayone** [comment]
perfect

**Comment by jaspermayone** [comment]
next didn't even warn me for some reason @aramshiva

**Comment by jaspermayone** [comment]
wait i think it's only the viewport tag that shouldn't be there @aramshiva

**Comment by aramshiva** [comment]
doesn't matter if they other ones are on `_app`.

**Comment by jaspermayone** [comment]
what's the difference?

**Comment by aramshiva** [comment]
no difference except the viewport

**Comment by jaspermayone** [comment]
why are there 2 different files then lol

**Comment by aramshiva** [comment]
Ohh, they `_app` is for the stuff needed to run Next.js related stuff, `_document` is for everything else

**Comment by jaspermayone** [comment]
Interesting

**Comment by jaspermayone** [comment]
is it worth moving to the new router type?

**Comment by jaspermayone** [comment]
(as a total aside)

**Pull request merged**
