### PR TITLE
Implement Back Button on Photos Page

### LINKED ISSUE #48: [BUG] No back button on photos page

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- No back button on photos page

## Issue ticket number and link:
- **Ticket Number:** [ 48 ]
- **Link:** [ https://github.com/jaspermayone/website/issues/48 ]

### Evidence:

image

### Acceptance Criteria:
- [x] Add Back Button on Photos Page

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @jaspermayone, Please review this PR.

**Comment by jaspermayone** [comment]
Hi @aliraza556, there's already code for a back button implemented, it just isn't working and needs to be fixed.

**Comment by aliraza556** [comment]
> Hi @aliraza556, there's already code for a back button implemented, it just isn't working and needs to be fixed.

@jaspermayone, Ok.

**Comment by jaspermayone** [comment]
@aliraza556 it's in the code, just not implemented in the element handler properly.

**Comment by aliraza556** [comment]
@jaspermayone, I couldn't find the BackButton implementation. Please guide me?

**Comment by aliraza556** [comment]
@jaspermayone, I reviewed the entire project code, and I only found the Button code, but I couldn't find any BackButton code.

https://github.com/jaspermayone/website/blob/main/src/components/ui/button.tsx

**Comment by jaspermayone** [comment]
@aliraza556 check out the code here, I do something very similar

https://github.com/jaspermayone/website/blob/b48a1e40a5784dc0357d7370515b991d477fed15/src/components/ui/friends.tsx#L42-L65

**Comment by aliraza556** [comment]
Hi @jaspermayone, Please review this PR:

image

**Review by jaspermayone — APPROVED** [review]

**Comment by aliraza556** [comment]
Hi @jaspermayone, could you please guide me on how to claim the bounty I was rewarded? Thanks in advance!

**Comment by jaspermayone** [comment]
@aliraza556 there's no specific bounty lol, that was more just myself reminding what issues I needed to work on and labeling high prio ones in case people wanted to work on them.

**Comment by jaspermayone** [comment]
You get my gratitude tho! 😄

**Comment by aliraza556** [comment]
> @aliraza556 there's no specific bounty lol, that was more just myself reminding what issues I needed to work on and labeling high prio ones in case people wanted to work on them.

@jaspermayone, I see, but using the `bounty` label was misleading. If something is just high priority, it should be labeled as such to avoid confusion. Please be more careful with labeling in the future.

**Comment by aliraza556** [comment]
@jaspermayone, If there wasn't a bounty, why label it that way? If it's just high priority, then please only use the high-priority label next time. It's confusing and misleading for contributors. Please be more careful in the future

**Pull request merged**
